# Generated by Django 4.1.3 on 2022-12-04 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="title",
            new_name="name",
        ),
    ]
