# Generated by Django 4.1.3 on 2022-12-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0005_alter_videoproxy_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
