# Generated by Django 4.1.3 on 2022-12-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0008_delete_videoproxy_videopublishedproxy"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="state",
            field=models.CharField(
                choices=[("PU", "Publish"), ("DR", "Draft")], default="DR", max_length=2
            ),
        ),
    ]
