# Generated by Django 4.1.3 on 2022-12-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0009_video_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="publish_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
