# Generated by Django 4.1.3 on 2022-12-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0010_video_publish_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="video",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
