# Generated by Django 4.1.3 on 2022-12-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0012_alter_video_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_id",
            field=models.CharField(max_length=220, unique=True),
        ),
    ]
