# Generated by Django 4.1.3 on 2022-12-08 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("playlists", "0006_alter_playlist_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playlist",
            name="videos",
        ),
    ]
